export const words = {
  headerTitle: "Shopping Cart",
  content: "Content",
  footerTitle: "© CopyWright Mohamed Sabry 2022",
  title: "Title:",
  qty: "Qty:",
  price: "Price: $",
  remove: "Remove",
  total: "Total: $",
  selectbtn: "Select Product",
  orderdone: "order done successfully",
  name: "Name:",
  email: "Email:",
  total2: "Total:",
  orderselect: "Selected Items:",
  type: "text",
  type2: "email",
  name2: "name",
  name3: "email",
  checkout: "Checkout",
  filter: "Filter",
  numberpro: "Number Of Products:",
  ALL: "ALL",
  XS: "XS",
  S: "S",
  M: "M",
  L: "L",
  XL: "XL",
  XXL: "XXL",
  order: "Order",
  Latest: "Latest",
  Lowest: "Lowest",
  Highest: "Highest",
  addcart: " Add To Cart",
};
